import { EmailMessage, Mailbox } from '../utils/types';

export const MOCK_USER_EMAIL = 'b.wilbers@koskamp.nl';
export const MOCK_USER_NAME = 'B. Wilbers';

export const mockMailboxes: Mailbox[] = [
  {
    id: 'mb-work',
    displayName: 'Werk (M365)',
    emailAddress: MOCK_USER_EMAIL,
    provider: 'm365',
    order: 0,
    selected: true,
  },
  {
    id: 'mb-gmail',
    displayName: 'Persoonlijk (Gmail)',
    emailAddress: 'b.wilbers@gmail.com',
    provider: 'gmail',
    order: 1,
    selected: true,
  },
  {
    id: 'mb-imap',
    displayName: 'Klantenservice (IMAP)',
    emailAddress: 'support@koskamp.nl',
    provider: 'imap',
    order: 2,
    selected: true,
  },
];

const user = { name: MOCK_USER_NAME, email: MOCK_USER_EMAIL };

export const mockMessages: EmailMessage[] = [
  {
    id: 'e1',
    mailboxId: 'mb-work',
    from: { name: 'Sanne de Vries', email: 's.devries@koskamp.nl' },
    to: [user],
    cc: [],
    bcc: [],
    subject: 'Contract review voor vrijdag nodig',
    preview: 'Kun je even kijken naar de bijgevoegde conceptovereenkomst...',
    body: 'Hoi, kun je even kijken naar de bijgevoegde conceptovereenkomst? Ik hoor graag voor vrijdag of er nog aanpassingen nodig zijn.\n\nGroet, Sanne',
    receivedAt: '2026-07-22T08:12:00Z',
    isRead: false,
    attachments: [{ id: 'a1', fileName: 'concept-overeenkomst.pdf', sizeKb: 340 }],
  },
  {
    id: 'e2',
    mailboxId: 'mb-work',
    from: { name: 'Team Planning', email: 'planning@koskamp.nl' },
    to: [user],
    cc: [
      { name: 'Mark Jansen', email: 'm.jansen@koskamp.nl' },
      { name: 'Lisa Bakker', email: 'l.bakker@koskamp.nl' },
    ],
    bcc: [],
    subject: 'Update planning Q3',
    preview: 'Bijgaand de bijgewerkte planning voor het derde kwartaal...',
    body: 'Bijgaand de bijgewerkte planning voor het derde kwartaal. Laat het weten als je nog wijzigingen hebt.',
    receivedAt: '2026-07-22T07:45:00Z',
    isRead: false,
    attachments: [],
  },
  {
    id: 'e3',
    mailboxId: 'mb-work',
    from: { name: 'Erik Smits', email: 'e.smits@partner-bv.nl' },
    to: [
      user,
      { name: 'Team Sales', email: 'sales@koskamp.nl' },
    ],
    cc: [],
    bcc: [],
    subject: 'Voorstel samenwerking 2026',
    preview: 'Naar aanleiding van ons gesprek stuur ik hierbij ons voorstel...',
    body: 'Naar aanleiding van ons gesprek stuur ik hierbij ons voorstel voor de samenwerking in 2026.',
    receivedAt: '2026-07-21T16:30:00Z',
    isRead: false,
    attachments: [{ id: 'a2', fileName: 'voorstel-2026.docx', sizeKb: 210 }],
  },
  {
    id: 'e4',
    mailboxId: 'mb-work',
    from: { name: 'Nieuwsbrief HR', email: 'hr-nieuws@koskamp.nl' },
    to: [{ name: 'Alle medewerkers', email: 'alle-medewerkers@koskamp.nl' }],
    cc: [],
    bcc: [user],
    subject: 'Personeelsuitje 2026 - save the date',
    preview: 'Zet alvast in je agenda: op 12 september organiseren we...',
    body: 'Zet alvast in je agenda: op 12 september organiseren we het jaarlijkse personeelsuitje.',
    receivedAt: '2026-07-21T09:00:00Z',
    isRead: false,
    attachments: [],
  },
  {
    id: 'e5',
    mailboxId: 'mb-gmail',
    from: { name: 'Marieke Peters', email: 'marieke.peters@gmail.com' },
    to: [user],
    cc: [],
    bcc: [],
    subject: 'Weekend weg?',
    preview: 'Hey! Zin om een weekendje weg te plannen in september?',
    body: 'Hey! Zin om een weekendje weg te plannen in september? Laat weten welk weekend jou uitkomt.',
    receivedAt: '2026-07-22T06:20:00Z',
    isRead: false,
    attachments: [],
  },
  {
    id: 'e6',
    mailboxId: 'mb-gmail',
    from: { name: 'Bol.com', email: 'noreply@bol.com' },
    to: [{ name: 'Klant', email: 'klant@bol.com' }],
    cc: [],
    bcc: [user],
    subject: 'Je bestelling is onderweg',
    preview: 'Goed nieuws! Je pakket is verzonden en komt morgen aan.',
    body: 'Goed nieuws! Je pakket is verzonden en komt morgen aan.',
    receivedAt: '2026-07-20T14:00:00Z',
    isRead: false,
    attachments: [],
  },
  {
    id: 'e7',
    mailboxId: 'mb-imap',
    from: { name: 'Klant - Fam. de Boer', email: 'deboer.familie@outlook.com' },
    to: [user],
    cc: [],
    bcc: [],
    subject: 'Vraag over factuur #4021',
    preview: 'Ik heb een vraag over de laatste factuur die ik heb ontvangen...',
    body: 'Ik heb een vraag over de laatste factuur die ik heb ontvangen, het bedrag klopt niet met de offerte.',
    receivedAt: '2026-07-21T11:10:00Z',
    isRead: false,
    attachments: [{ id: 'a3', fileName: 'factuur-4021.pdf', sizeKb: 95 }],
  },
  {
    id: 'e8',
    mailboxId: 'mb-imap',
    from: { name: 'Klant - J. Alberts', email: 'j.alberts@live.nl' },
    to: [user],
    cc: [{ name: 'Support Team', email: 'support@koskamp.nl' }],
    bcc: [],
    subject: 'Klacht over levertijd',
    preview: 'Mijn bestelling zou vorige week al binnen zijn, dit duurt te lang.',
    body: 'Mijn bestelling zou vorige week al binnen zijn, dit duurt te lang. Graag snel een reactie.',
    receivedAt: '2026-07-20T10:00:00Z',
    isRead: false,
    attachments: [],
  },
];
